### ISSUE TITLE
How to repack to 'Files.N2PK'

### ISSUE THREAD

**Issue by XHXIAIEIN** [mome-borogove/40K-n2pk-converter#1] opened 2020-12-27 09:42 UTC
I'm playing Deathtrap, But the developers didn't provide my native language, so i wanted to translate it themselves.
'unpack-n2pk.py' It works well!  But how do re-converter to the 'Files.N2PK'?

**Comment by mome-borogove** [comment] 2020-12-27 10:17
As far as N2PK files go, it's a one-way deal. There are hashes in some of the file headers, and we don't have access to the function used. As far as I can tell, these are indeed checked by the game client upon load, and if they don't match, then the game crashes to desktop immediately. It's unclear if these are for game integrity, anti-cheat, or both, but regardless, they make going backwards impossible. I've written a tool that goes backwards, but without the hash function, it's useless.

That said, if Deathtrap is like W40K: Inquisitor, localization isn't actually handled in N2PK files. There's an entirely separate set of XML files which control that. These files are *not* hashed, and I've confirmed that modifications to those files *are* reflected in-game. In other words, you can manually change those files at your heart's content and it should show up.

Now, on a scale of 1 to "Unsupported", this is about a 15, so I wouldn't expect this to go easily. For one, you'd better make sure that you're doing all of your work in a separate directory, since auto-updates (like Steam) will overwrite whatever you've done every time the game updates. Two, there's no guarantees that the new strings will look right. It looks like you might be looking to translate to Chinese, which means you have to hope that that game's fonts will render the character set correctly. W40K: Inquisitor has native support for Chinese, but that doesn't really guarantee anything for Deathtrap (and I know next to nothing about the game, sorry).

Anyways, I'm going to close this issue since I have tried going both ways and there's some fundamental blockers to doing so, but I hope I've given you a lead on an alternate direction to go in.

**Closed as completed by mome-borogove** 2020-12-27 10:17 UTC

**Comment by XHXIAIEIN** [comment] 2020-12-27 10:18
> As far as N2PK files go, it's a one-way deal. There are hashes in some of the file headers, and we don't have access to the function used. As far as I can tell, these are indeed checked by the game client upon load, and if they don't match, then the game crashes to desktop immediately. It's unclear if these are for game integrity, anti-cheat, or both, but regardless, they make going backwards impossible. I've written a tool that goes backwards, but without the hash function, it's useless.
> 
> That said, if Deathtrap is like W40K: Inquisitor, localization isn't actually handled in N2PK files. There's an entirely separate set of XML files which control that. These files are _not_ hashed, and I've confirmed that modifications to those files _are_ reflected in-game. In other words, you can manually change those files at your heart's content and it should show up.
> 
> Now, on a scale of 1 to "Unsupported", this is about a 15, so I wouldn't expect this to go easily. For one, you'd better make sure that you're doing all of your work in a separate directory, since auto-updates (like Steam) will overwrite whatever you've done every time the game updates. Two, there's no guarantees that the new strings will look right. It looks like you might be looking to translate to Chinese, which means you have to hope that that game's fonts will render the character set correctly. W40K: Inquisitor has native support for Chinese, but that doesn't really guarantee anything for Deathtrap (and I know next to nothing about the game, sorry).
> 
> Anyways, I'm going to close this issue since I have tried going both ways and there's some fundamental blockers to doing so, but I hope I've given you a lead on an alternate direction to go in.


Thank! I unpack N2PK get some the XML file, and move it back in the game language folder, it can be read in the game, thank you very much!
